# Generated by Django 3.2.9 on 2021-11-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_productmodel_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
